apiVersion: v1
kind: ResourceQuota
metadata:
  name: mi-resource-quota
  namespace: mi-namespace
spec:
  hard:
    deployments.apps: "3"
    secrets: "2"
    configmaps: "2"
    services: "3"
